login:
    pattern:   /login
    defaults:  { _controller: DashboardBundle:Security:login }
login_check:
    pattern:   /login_check

logout:
    path: /logout

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
