login:
    path:   /login
    defaults:  { _controller: DashboardBundle:Security:login }
login_check:
    path:   /login_check

logout:
    path: /logout

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
